travis:
  secure:
    BINSTAR_TOKEN: Xq4rLTdIjiobjXZRsLBH8wAdn6U8qtxyILZ8EYZFtoj111HPWhdSlPpKblaM/HXIzK+5ujPakWrPvcC4rp97RNddCZHtqjlw1SEUGIl2s+joXsThXzqnVjs2biylDPW+0Qj6tg6LAPiu+3DMcwVZsAQNg90Y42RD2vUQqpeENMDT5zG+FbAE9CmlTDlbbJYkjAsi74qysDCiBb3YhwdvutSzPGrWLqj+c6FbmUImblbumMZFNEH3RMxxImfqjDflQj6B2JBp8P3bkdDIYe262nmPsbLxd5kI+J36DOn4jeu8AxGgCyAwo0KxlFn/s2gny55qU4RLGx6a/U3OX5/TaXiaMlWtprkefhDwkXWxjE76VgAe597v2/qiiMl9XRgtMW6Ojs4ClgWA8K937j/qRJSLMZ5jZV0P78A99bjmCLp5t+SePLaDYQBz1paUAqSQsC8ZLnonhxppyc+bMTW2Q3ij2aHUr6DsAoLPoQLh4t0nip4f3IOrKI2VPpA8KKzU7umleP8iB9oPoBxjZoftCJW291/hSSpZCiXX9qac86cDAHuh5hF2SEKAgu+nottbWsqQLpFGdF3t3KEzGa7yDYeNrsyymJcce/SHCf/cVgLxKpW9dGjeT3D/3Upu0dwB0bcFqiP/RhEArsRq2oHHlj7BaeDxrpuaFPyct0rXbnk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
